version: 0.2

phases:
  build:
    commands:
      - echo Build For pokemon-management has started.
      - mvn clean package
  post_build:
    commands:
      - echo Build For pokemon-management has Completed Successful.
artifacts:
  files:
    - target/pokemon-management.jar
  discard-paths: yes